In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
n = np.random.randint(0,10,size=(2,3))
n

array([[3, 3, 3],
       [6, 1, 3]], dtype=int32)

一，矩阵的普通运算

    1，与数的运算

In [7]:
n1 = n + 10 #加+
n2 = n - 10 #减-
n3 = n * 10 #乘*
n4 = n / 10 #除/
n5 = n // 2 #整除//(求商)
n6 = n ** 2 #次方**
n7 = n % 3 #求模%
display(n1,n2,n3,n4,n5,n6,n7)

array([[13, 13, 13],
       [16, 11, 13]], dtype=int32)

array([[-7, -7, -7],
       [-4, -9, -7]], dtype=int32)

array([[30, 30, 30],
       [60, 10, 30]], dtype=int32)

array([[0.3, 0.3, 0.3],
       [0.6, 0.1, 0.3]])

array([[1, 1, 1],
       [3, 0, 1]], dtype=int32)

array([[ 9,  9,  9],
       [36,  1,  9]], dtype=int32)

array([[0, 0, 0],
       [0, 1, 0]], dtype=int32)

    2,与矩阵的运算

In [8]:
n1 = np.random.randint(0,10,size=(4,6))
n2 = np.random.randint(0,10,size=(4,6))
display(n1,n2)

array([[8, 5, 7, 7, 7, 6],
       [3, 8, 9, 2, 7, 5],
       [6, 0, 8, 4, 4, 6],
       [1, 3, 3, 7, 8, 4]], dtype=int32)

array([[8, 8, 5, 1, 2, 8],
       [1, 0, 8, 5, 9, 3],
       [9, 1, 5, 2, 9, 2],
       [4, 1, 0, 7, 2, 7]], dtype=int32)

In [9]:
#加(对应元素相加)
m1 = n1 + n2
#减相似
#乘*
m2 = n1 * n2
display(m1,m2)

array([[16, 13, 12,  8,  9, 14],
       [ 4,  8, 17,  7, 16,  8],
       [15,  1, 13,  6, 13,  8],
       [ 5,  4,  3, 14, 10, 11]], dtype=int32)

array([[64, 40, 35,  7, 14, 48],
       [ 3,  0, 72, 10, 63, 15],
       [54,  0, 40,  8, 36, 12],
       [ 4,  3,  0, 49, 16, 28]], dtype=int32)

二，线性代数

    1，矩阵积
       np.dot(n1,n2)
       n1的列数 = n2的行数

In [10]:
n1 = np.random.randint(0,10,size=(4,6))
n2 = np.random.randint(0,10,size=(6,5))
display(n1,n2)

array([[7, 4, 2, 3, 0, 6],
       [0, 1, 7, 6, 5, 3],
       [9, 2, 3, 0, 1, 5],
       [6, 9, 2, 7, 9, 3]], dtype=int32)

array([[7, 4, 1, 2, 4],
       [6, 5, 4, 1, 2],
       [2, 0, 0, 8, 5],
       [8, 0, 7, 4, 7],
       [8, 3, 0, 7, 7],
       [4, 5, 9, 6, 3]], dtype=int32)

In [11]:
np.dot(n1,n2)

array([[125,  78,  98,  82,  85],
       [120,  35,  73, 134, 123],
       [109,  74,  62,  81,  77],
       [240, 111, 118, 146, 173]], dtype=int32)

    2,其他常见操作

In [12]:
n = np.array([[1,2,5],
              [3,7,3],
              [2,4,9]])
n

array([[1, 2, 5],
       [3, 7, 3],
       [2, 4, 9]])

In [13]:
#矩阵的逆
np.linalg.inv(n)

array([[-51.,  -2.,  29.],
       [ 21.,   1., -12.],
       [  2.,   0.,  -1.]])

In [14]:
#矩阵的行列式
np.linalg.det(n)

np.float64(-0.9999999999999992)

In [16]:
#矩阵的秩(仅方阵)
np.linalg.matrix_rank(n)
#rank <= 矩阵的阶数
#等于为满秩矩阵
#小于为奇异矩阵

np.int64(3)

三，广播机制

    1为缺失的维度补维度
    2，缺失的元素用已有的补充

In [19]:
m = np.ones((3,2))
a = np.arange(2)
display(m,a)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([0, 1])

In [21]:
m + a
#为a添加了一个维度
#即a = array([[0,1],
#             [0,1]])

array([[1., 2.],
       [1., 2.],
       [1., 2.]])

In [23]:
a = np.arange(3).reshape((-1,1))
b = np.arange(3)                         
display(a,b)

array([[0],
       [1],
       [2]])

array([0, 1, 2])

In [25]:
a + b
#为a，b填充维度
#即a = array([[0,0,0],      
#             [1,1,1]，
#             [2,2,2]])
#即b = array([[0,1,2],      
#             [0,1,2]，
#             [0,1,2]])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])