In [1]:
import numpy as np

一，保存ndarray

In [4]:
x = np.arange(4)
y = np.arange(43,68)

#save保存成一个npy文件
np.save('x',x)

#savez保存成一个npz文件
np.savez('arr.npz',xarr=x,yarr=y)

二，读取ndarray

In [8]:
#读npy文件
np.load('x.npy')

#读npz文件
np.load('arr.npz')['xarr']

array([0, 1, 2, 3])

三，csv，txt读写

In [10]:
n = np.random.randint(0,10,size=(3,5))
n

array([[0, 9, 0, 5, 8],
       [4, 1, 4, 2, 6],
       [8, 9, 9, 7, 5]], dtype=int32)

In [12]:
#存储到csv或txt
np.savetxt('arr.txt',n)
#delimiter分割符
np.savetxt('arr.csv',n,delimiter=',')

In [17]:
#读取csv或txt
np.loadtxt('arr.csv',delimiter=',',dtype=np.int16)

C:\Users\freedom\AppData\Local\Temp\ipykernel_11988\4113544725.py:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  np.loadtxt('arr.csv',delimiter=',',dtype=np.int16)


array([[0, 9, 0, 5, 8],
       [4, 1, 4, 2, 6],
       [8, 9, 9, 7, 5]], dtype=int16)